Models/Instructions.cs
using Newtonsoft.Json;

namespace Renipe.Models
{

    //public class Instructions
    //{
    //    public string name { get; set; }
    //    public List<Step> steps { get; set; }
    //}

    //public class Step
    //{

    //    public string step { get; set; }
 
    //}

    public class Instructions
    {
        public double number { get; set; }
        public string unit { get; set; }
    }
}

Controllers/NutritionFactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Renipe.DataContext;
using Renipe.Models;
using System.Net.Http.Headers;
using Newtonsoft.Json;
using System.Net.WebSockets;
using Microsoft.Build.Construction;

namespace Renipe.Controllers
{
    public class NutritionFactsController : Controller
    {
        private readonly RenipeDBContext _context;

        HttpClient client = new();

        static FdcResults jsData = new();

        static List<DayView> days = new();

        public NutritionFactsController(RenipeDBContext context)
        {
            _context = context;
        }

        // GET: NutritionFacts
        public async Task<IActionResult> Index()
        {
              return View(await _context.NutritionData.OrderByDescending(i => i.Date).Select(m => m.ToDisplay()).ToListAsync());
        }

        public IActionResult Search()
        {
            return View();
        }

        public async Task<IActionResult> Results(Search model)
        {
            if(client.BaseAddress == null)
            {
                client.BaseAddress = new Uri("https://api.nal.usda.gov/fdc/v1/foods/search");
            }
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(
                new MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage response = await client.GetAsync(client.BaseAddress.ToString() + "?query=" + model.SearchString + "&api_key=" + "beRFFWSIsr5S5dntcc8JS1tFscBHd5mtbkonR5Ps");
            if (response.IsSuccessStatusCode)
            {
                var jstr = await response.Content.ReadAsStringAsync();
                jsData = JsonConvert.DeserializeObject<FdcResults>(jstr);
                return View(jsData);
            }
            else
            {
                return Content("No Food Items Found");
            }

        }

        // GET: NutritionFacts/NutritionDetails/5
        public async Task<IActionResult> NutritionDetails(int? id)
        {
            if (id == null || jsData.foods == null)
            {
                return NotFound();
            }

            var nutritionFacts = jsData.foods.FirstOrDefault(f => f.fdcId == id).ToModel();
            if (nutritionFacts == null)
            {
                return NotFound();
            }
            return View(nutritionFacts);
        }

        // GET: NutritionFacts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.NutritionData == null)
            {
                return NotFound();
            }

            var meal = _context.NutritionData.FirstOrDefault(f => f.MealId == id);
            if (meal == null)
            {
                return NotFound();
            }

            return View(meal.ToDisplay());
        }

        // GET: NutritionFacts/Create
        [HttpGet]
        public IActionResult Create(NutritionFacts nutritionItem)
        {
            return View(nutritionItem.ToMeal());
        }

        // POST: NutritionFacts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MealId,FoodName,CaloriesPerServing,CarbohydratesPerServing,ProteinPerServing,FatPerServing,PhosphorusPerServing,PotassiumPerServing,SodiumPerServing,Servings,Date")] Meal meal)
        {
            if (ModelState.IsValid)
            {
                _context.Add(meal);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(meal);
        }

        // GET: NutritionFacts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.NutritionData == null)
            {
                return NotFound();
            }

            var nutritionFacts = await _context.NutritionData.FindAsync(id);
            if (nutritionFacts == null)
            {
                return NotFound();
            }
            return View(nutritionFacts);
        }

        // POST: NutritionFacts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MealId,FoodName,CaloriesPerServing,CarbohydratesPerServing,ProteinPerServing,FatPerServing,PhosphorusPerServing,PotassiumPerServing,SodiumPerServing,Servings,Date")] Meal meal)
        {
            if (id != meal.MealId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(meal);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NutritionFactsExists(meal.MealId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(meal);
        }

        // GET: NutritionFacts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.NutritionData == null)
            {
                return NotFound();
            }

            var nutritionFacts = await _context.NutritionData
                .FirstOrDefaultAsync(m => m.MealId == id);
            if (nutritionFacts == null)
            {
                return NotFound();
            }

            return View(nutritionFacts);
        }

        // POST: NutritionFacts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.NutritionData == null)
            {
                return Problem("Entity set 'RenipeDBContext.NutritionData'  is null.");
            }
            var nutritionFacts = await _context.NutritionData.FindAsync(id);
            if (nutritionFacts != null)
            {
                _context.NutritionData.Remove(nutritionFacts);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool NutritionFactsExists(int id)
        {
          return _context.NutritionData.Any(e => e.MealId == id);
        }

        public async Task<IActionResult> DailyView()
        {
            days = new();
            IEnumerable<IGrouping<DateTime, Meal>> groupings = _context.NutritionData.GroupBy(m => m.Date);
            foreach(var g in groupings)
            {
                List<Meal> meals = g.ToList();
                DayView day = new DayView(meals);
                days.Add(day);
            }
            return View(days.OrderByDescending(d => d.date));
        }

        public IActionResult DailyViewDetails(int id)
        {
            var date = days.FirstOrDefault(d => d.Id == id).date;
            List<Meal> meals = _context.NutritionData.Where(m => m.Date == date).ToList();
            return View(meals);
        }
    }
}

Controllers/PropertyModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Renipe.DataContext;
using Renipe.Models;

namespace Renipe.Controllers
{
    public class PropertyModelsController : Controller
    {
        private readonly RenipeDBContext _context;

        public PropertyModelsController(RenipeDBContext context)
        {
            _context = context;
        }

        // GET: PropertyModels
        public async Task<IActionResult> Index()
        {
              return View(await _context.PropertyRecipe.ToListAsync());
        }

        // GET: PropertyModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.PropertyRecipe == null)
            {
                return NotFound();
            }

            //var propertyModel = await _context.PropertyRecipe
            //    .FirstOrDefaultAsync(m => m.ID == id);
            var propertyModel = await _context.PropertyRecipe.FindAsync(id);
            if (propertyModel == null)
            {
                return NotFound();
            }

            //return View(propertyModel);
            return RedirectToAction("RecipeInfo", "Home", new { id = propertyModel.RecipeId });

            //return RedirectToAction("RecipeInfo/" + PropertyModel.ID, "Home");
        }

        // GET: PropertyModels/Create
        public IActionResult Create()
        {
            PropertyModel data = new PropertyModel()
            {
                RecipeId = int.Parse(TempData["mydata"].ToString()),
                Title = TempData["mydata2"].ToString(),
                SourceUrl = TempData["mydata3"].ToString()
            };
            //PropertyModel data = TempData["mydata"] as PropertyModel;
            //var propertyModel = _context.RecipeData.FindAsync(data.ID);
            return View(data);
        }

        // POST: PropertyModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,RecipeId,Title,SourceUrl")] PropertyModel propertyModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(propertyModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(propertyModel);
        }

        // GET: PropertyModels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.PropertyRecipe == null)
            {
                return NotFound();
            }

            var propertyModel = await _context.PropertyRecipe.FindAsync(id);
            if (propertyModel == null)
            {
                return NotFound();
            }
            return View(propertyModel);
            //return View();
        }

        // POST: PropertyModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Title,SourceUrl")] PropertyModel propertyModel)
        {
            if (id != propertyModel.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(propertyModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PropertyModelExists(propertyModel.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(propertyModel);
            //return View();
        }

        // GET: PropertyModels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.PropertyRecipe == null)
            {
                return NotFound();
            }

            var propertyModel = await _context.PropertyRecipe
                .FirstOrDefaultAsync(m => m.ID == id);
            if (propertyModel == null)
            {
                return NotFound();
            }

            return View(propertyModel);
        }

        // POST: PropertyModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.PropertyRecipe == null)
            {
                return Problem("Entity set 'RenipeDBContext.PropertyRecipe'  is null.");
            }
            var propertyModel = await _context.PropertyRecipe.FindAsync(id);
            if (propertyModel != null)
            {
                _context.PropertyRecipe.Remove(propertyModel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PropertyModelExists(int id)
        {
          return _context.PropertyRecipe.Any(e => e.ID == id);
        }
    }
}

Views/Shared/InstructionsView.cshtml
@*@model List<Root>*@
    @model RecipeData
@{
    ViewData["Title"] = "RecipeInstruction";
}

@*<p>@Html.DisplayFor(model => model.steps)</p>*@
@*<div>
     @foreach (RecipeData item in Model)
    {
    <p>
            @Html.DisplayFor(model => item.steps)
     </p>
    }
</div>*@

Views/Shared/SummaryView.cshtml
@model RecipeData
@{
    ViewData["Title"] = "RecipeSummary";
}



@*<p>@Html.DisplayFor(model => model.Summary)</p>*@
<p>@Html.Raw(Model.Summary)</p>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Renipe</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Renipe.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Renipe</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NutritionFacts" asp-action="DailyView">Daily View</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PropertyModels" asp-action="Index">Saved</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NutritionFacts" asp-action="Search">FDC Search</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NutritionFacts" asp-action="Index">All Tracked Meals</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Renipe - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>